staffmessage: Version 2.0 Staff message.
buildermessage: Version 2.0 Builder message.
membermessage: Version 2.0 Member message.



commands: &5 /cm set &2staff \n &5 /cm set &2member \n &5 /cm set &2builder \n &5 /cm set &2gladiator \n &5 /cm set &2navigation
