name: CleggehMessage
version: 2.3
main: org.matecraft.cleggeh.cleggehmessage2.CleggehMessage
author: Cleggeh
description: >
             A simple Message Plugin.
commands:
    staff:
        desciption: Use this command to see how to become staff!
        
    navigation:
        desciption: Use this command to see how to Navigate around the server!
        
    member:
        desciption: Use this command to see how to become member!
        
    gladiator:
        desciption: Use this command to see how to become gladiator!
        
    navigation:
        desciption: Use this command to see how to become member!
        
    builder:
        desciption: Use this command to see how to become builder!
        
    teamspeak:
        desciption: Use this command to see the IP for teamspeak!
        
    claiming:
        desciption: Use this command to find out how to claim land!
        
    color:
        desciption: Use this command to get Color codes!
        aliases: [color, format]
        
    cm:
        desciption: Use this command to set info.
        
    addperm:
        desciption: Adds permissions to all server worlds
permissions:
    cleggehMessage.admin:
        default: op
    cleggehmessage.color:
        default: op
    cleggehmessage.add:
        default: op