name: CleggehMessage
version: 2.1
main: org.matecraft.cleggeh.cleggehmessage2.CleggehMessage
author: Cleggeh
description: >
             A simple Message Plugin.
commands:
    staff:
        desciption: Use this command to see how to become staff!
        
    navigation:
        desciption: Use this command to see how to Navigate around the server!
        
    member:
        desciption: Use this command to see how to become member!
        
    gladiator:
        desciption: Use this command to see how to become gladiator!
        
    navigation:
        desciption: Use this command to see how to become member!
        
    builder:
        desciption: Use this command to see how to become builder!
        
    color:
        desciption: Use this command to get Color codes!
        aliases: [color, format]
        
    cm:
        desciption: Use this command to set info.
permissions:
    cleggehMessage.admin:
        default: op
    cleggehmessage.color:
        default: op
    cleggehmessage.add:
        default: op